name: Deploy via Ansible

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.ANSIBLE_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via Ansible server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.ANSIBLE_EC2_USER }}@${{ secrets.ANSIBLE_EC2_HOST }} '
            cd ~/ansible-onixmall &&
            source venv/bin/activate &&
            ansible-playbook -i inventory.ini deploy.yml
          '
